### ISSUE TITLE
Inkplate6COLOR v2.0.0 Definition Does Not Work on Arduino IDE 2.0.2 on Windows

### ISSUE THREAD

**Issue by JSylvia007** [SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE#1]
There is a board definition as well as an upload bandwidth error.

**Comment by BornaBiro** [comment]
Hello JSylvia007.

Please can you be more specific about the problem? Is the board missing from the board definition or compile/upload is failing? Or is it something else?

Any screenshots, C/P of the error, as well as the name of the operating system (Win, macOS, Linux) which is running Arduino IDE would be helpful.

**Comment by avdg** [comment]
Hi, I'm not sure if this is related, though this is an issue on the arduino ide 2.0 too.

I am compiling code for the arduino 6plus and while I have no issues on ide 1.8, I do have issues on my freshly installed 2.0 ide (luckily not overwriting my older ide).

On 2.0, I can't even verify if the code is working properly because of this error:

![arduino-ide-2_ 0_3-error](https://user-images.githubusercontent.com/212248/206564394-7caf6311-5444-4ab6-bcbd-8a70dfa9e833.png)

There seems not to be an option to adjust the upload speed in ide 2.0 (yep, the menu highlight shows the menu left is selected, but the extended menu is the right one)

![arduino-ide-2_ 0_3-options](https://user-images.githubusercontent.com/212248/206564531-3d107752-807a-4a0c-9e93-2c1e98e1dca3.png)

While there is one for ide 1.8

![arduino-ide-1_8_57-options](https://user-images.githubusercontent.com/212248/206564618-9c3319ca-5dd8-4030-984b-fcb5e82e9f22.png)

**Comment by phaughton** [comment]
I'm seeing the exact same error.

**Comment by BornaBiro** [comment]
Hello everybody!

First, sorry for my late reply.
For some reason, the new Arduino IDE 2.0 does not handle the old style of defining upload speed parameter very well.
The new version of the Inkplate Board Definition should fix this issue (Inkplate Board Definition v3.0.0).
